In [17]:
import numpy as np

In [38]:
myarr1=np.array([1,"hry",3,4,5]) #1-D array

In [39]:
myarr1[1] #accessing 1-D array

np.str_('hry')

In [23]:
myarr2=np.array([[1,2,3,4,5]], np.int64) #2-D array

In [24]:
myarr2[0,0]

np.int64(1)

In [33]:
myarr2.shape  #shape of the myarr2: has 1 row and 5 columns


(1, 5)

In [34]:
myarr1.shape  #shape of the myarr1: has 1 row 

(5,)

In [40]:
myarr1.dtype

dtype('<U21')

In [46]:
a = np.array([[1, 2, 3],[4, 5, 6]])
              
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a=np.array([1, 3, 4, 5, 6])

In [48]:
a

array([1, 3, 4, 5, 6])

In [49]:
a[0]

np.int64(1)

In [58]:
a=np.arange(10)**3

In [59]:
a[2]

np.int64(8)

In [60]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [63]:
a[2:5]  #the last indes i.e 5 will not be displayed

array([ 8, 27, 64])

In [64]:
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [66]:
a[::-1]  # to print in the reverse order

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [75]:
for i in a:
    print(i**(1 / 3.))  #cube of i eg. 1^3=1, 8^3=64

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [82]:
a[0]=9

In [83]:
a

array([  9,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [84]:
a[:]

array([  9,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [85]:
a[:3]

array([9, 1, 8])

In [86]:
b=a[:3]

In [87]:
b

array([9, 1, 8])

In [105]:
xarray=np.arange(12).reshape((3,4))  #reshape gives the NXM matrix row and columns

In [106]:
xarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
yarray=np.array([1,2,3,4,5,6],dtype=np.int16).reshape(2,3)

In [114]:
yarray

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [115]:
yarray.strides

(6, 2)