In [327]:
import numpy as np

In [328]:
x=np.arange(0,20,2)

In [329]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [330]:
y=x**2

In [331]:
y

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [332]:
y[:-1]

array([  0,   4,  16,  36,  64, 100, 144, 196, 256])

In [333]:
y[1:]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324])

In [334]:
x[1:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [335]:
x[:-1]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [336]:
y[1:]-y[:-1]

array([ 4, 12, 20, 28, 36, 44, 52, 60, 68])

In [337]:
x[1:]-x[:-1]

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [338]:
dy_dx = (y[1:]-y[:-1])/(x[1:]-x[:-1])

In [339]:
dy_dx

array([ 2.,  6., 10., 14., 18., 22., 26., 30., 34.])

In [340]:
x[:6]

array([ 0,  2,  4,  6,  8, 10])

In [341]:
lispace=np.linspace(1,5,3)

In [342]:
lispace

array([1., 3., 5.])

In [343]:
for i in lispace:
    print(i)

1.0
3.0
5.0


In [344]:
lispace.argmax()

np.int64(2)

In [345]:
lispace.max()

np.float64(5.0)

In [346]:
lispace.argmax()

np.int64(2)

In [347]:
lispace.argmin()

np.int64(0)

In [348]:
lispace.min()


np.float64(1.0)

In [349]:
y1=y.reshape(5,2)

In [350]:
y1

array([[  0,   4],
       [ 16,  36],
       [ 64, 100],
       [144, 196],
       [256, 324]])

In [351]:
y1.argmax()

np.int64(9)

In [352]:
y1.argsort()

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [353]:
y1[0][1]=789

In [354]:
y1

array([[  0, 789],
       [ 16,  36],
       [ 64, 100],
       [144, 196],
       [256, 324]])

In [355]:
y1.argsort(axis=0)

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4],
       [4, 0]])

In [356]:
y1.argmax(axis=0)   #to find the largest element's index

array([4, 0])

In [357]:
y1.argmax(axis=1)

array([1, 1, 1, 1, 1])

In [358]:
y2=y1.sort()

In [359]:
print(y2)

None


In [360]:
arr=np.array([0,2,3,4,5,6,7,8,9,2,3,5,6,])

In [361]:
arr=np.arange(0,40,2)

In [362]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [365]:
arr1=arr.reshape(5,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [368]:
arr1.argmax(axis=1)

array([3, 3, 3, 3, 3])

In [370]:
arr1.argmin(axis=0)

array([0, 0, 0, 0])

In [376]:
arr1[0][0]=6

In [377]:
arr1

array([[  6,   2,   4, 675],
       [  8,  10,  12,  14],
       [ 16,  18,  20,  22],
       [ 24,  26,  28,  30],
       [ 32,  34,  36,  38]])

In [379]:
arr1.argmax(axis=1)

array([3, 3, 3, 3, 3])