In [164]:
import numpy as np

In [165]:
a=np.array([1,3,5])

In [166]:
a

array([1, 3, 5])

In [167]:
b=[3*x for x in a]

In [168]:
b

[np.int64(3), np.int64(9), np.int64(15)]

In [169]:
c=b-a#(vector A - vector B)

In [170]:
c

array([ 2,  6, 10])

In [171]:
m=np.arange(6).reshape(2,3)

In [172]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [173]:
m+c   # the order of mXn can be added to mXn if n is same

array([[ 2,  7, 12],
       [ 5, 10, 15]])

In [174]:
d=np.arange(9).reshape(3,3)

In [175]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [176]:
d+c

array([[ 2,  7, 12],
       [ 5, 10, 15],
       [ 8, 13, 18]])

In [177]:
x=np.array([2, 4, 3])
y=np.array([2, 4])

In [178]:
def f(x):
    return x**2-3*x+4


In [179]:
x = np.arange(1e5)

In [180]:
y = [f(i) for i in x]

In [181]:
y=f(x)

In [182]:
y

array([4.00000000e+00, 2.00000000e+00, 2.00000000e+00, ...,
       9.99910002e+09, 9.99930001e+09, 9.99950001e+09], shape=(100000,))

In [188]:
d.sum(axis=0)

array([ 9, 12, 15])

In [189]:
d.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])